# Generated by Django 5.2.6 on 2026-01-31 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('pcs', 'Piece'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('box', 'Box'), ('pack', 'Pack'), ('set', 'Set'), ('bag', 'Bag'), ('ton', 'Ton')], default='pcs', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('port_count', models.IntegerField(blank=True, default=1, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True)),
                ('note', models.TextField(blank=True)),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='users.region')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Import (idxal/giriş)'), ('out', 'Export (ixrac/çıxış)'), ('transfer', 'Transfer (köçürmə)'), ('adjust', 'Adjustment (korreksiya)'), ('return', 'Return (qayıtma)')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_old', models.DecimalField(decimal_places=3, max_digits=18)),
                ('quantity_new', models.DecimalField(decimal_places=3, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_no', models.CharField(blank=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.product')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_out_movements', to='warehouse.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in_movements', to='warehouse.warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='warehouse.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouse.warehouse')),
            ],
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['region', 'name'], name='warehouse_w_region__1cad12_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='warehouse_w_is_acti_5ddb4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('region', 'name')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'created_at'], name='warehouse_s_warehou_4eeaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='warehouse_s_product_eae43e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='warehouse_s_movemen_7e8f40_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_no'], name='warehouse_s_referen_f74410_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinventory',
            index=models.Index(fields=['warehouse'], name='warehouse_w_warehou_cc7bca_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinventory',
            index=models.Index(fields=['product'], name='warehouse_w_product_42701a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinventory',
            index=models.Index(fields=['warehouse', 'product'], name='warehouse_w_warehou_321adc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseinventory',
            unique_together={('warehouse', 'product')},
        ),
    ]
