# Generated by Django 5.2.6 on 2026-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='returned_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
