# Generated by Django 5.2.6 on 2026-01-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='only_owner_can_send',
            field=models.BooleanField(default=False),
        ),
    ]
