# Generated by Django 5.2.6 on 2026-01-31 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='services/logos/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=60)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('date', 'Date'), ('datetime', 'Datetime'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tasks.service')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['service', 'key'], name='tasks_colum_service_50c221_idx'), models.Index(fields=['service', 'field_type'], name='tasks_colum_service_e434eb_idx')],
                'unique_together': {('service', 'key')},
            },
        ),
    ]
