# Generated by Django 5.2.6 on 2026-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='logo',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='AppstoreOutlined', max_length=50),
        ),
    ]
