# Generated by Django 5.2.6 on 2026-02-04 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='users.region'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='column',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tasks.service'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.customer'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='users.group'),
        ),
        migrations.AddField(
            model_name='task',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.service'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tasks.shelf'),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.stockmovement'),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_documents', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_products', to='warehouse.product'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_products', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_products', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='taskservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_services', to='tasks.service'),
        ),
        migrations.AddField(
            model_name='taskservice',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_services', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskservicevalue',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_values', to='tasks.column'),
        ),
        migrations.AddField(
            model_name='taskservicevalue',
            name='task_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tasks.taskservice'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasktype'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['service', 'key'], name='tasks_colum_service_50c221_idx'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['service', 'field_type'], name='tasks_colum_service_e434eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('service', 'key')},
        ),
        migrations.AddIndex(
            model_name='taskdocument',
            index=models.Index(fields=['task'], name='tasks_taskd_task_id_d5e8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdocument',
            index=models.Index(fields=['warehouse'], name='tasks_taskd_warehou_75788e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdocument',
            index=models.Index(fields=['confirmed'], name='tasks_taskd_confirm_75b19a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdocument',
            index=models.Index(fields=['shelf'], name='tasks_taskd_shelf_i_310909_idx'),
        ),
        migrations.AddIndex(
            model_name='taskproduct',
            index=models.Index(fields=['task'], name='tasks_taskp_task_id_4aa698_idx'),
        ),
        migrations.AddIndex(
            model_name='taskproduct',
            index=models.Index(fields=['product'], name='tasks_taskp_product_43a968_idx'),
        ),
        migrations.AddIndex(
            model_name='taskproduct',
            index=models.Index(fields=['warehouse'], name='tasks_taskp_warehou_6cc448_idx'),
        ),
        migrations.AddIndex(
            model_name='taskservice',
            index=models.Index(fields=['task'], name='tasks_tasks_task_id_d8ace8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskservice',
            index=models.Index(fields=['service'], name='tasks_tasks_service_964d06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskservice',
            unique_together={('task', 'service')},
        ),
        migrations.AddIndex(
            model_name='taskservicevalue',
            index=models.Index(fields=['task_service'], name='tasks_tasks_task_se_fd8475_idx'),
        ),
        migrations.AddIndex(
            model_name='taskservicevalue',
            index=models.Index(fields=['column'], name='tasks_tasks_column__ea3534_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskservicevalue',
            unique_together={('task_service', 'column')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['customer'], name='tasks_task_custome_8a09c5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='tasks_task_assigne_ab55af_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['group'], name='tasks_task_group_i_b1ce1d_idx'),
        ),
    ]
