# Generated by Django 5.2.6 on 2026-02-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdocument',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='stock_movement',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
        migrations.DeleteModel(
            name='TaskDocument',
        ),
    ]
