# Generated by Django 5.2.6 on 2026-01-31 15:57

import django.db.models.deletion
import tasks.models.task
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_service_logo_service_icon'),
        ('users', '0003_user_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('register_number', models.CharField(blank=True, max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='customers/passports/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_coordinates', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='users.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Gözləyir'), ('in_progress', 'İcrada'), ('arrived', 'Çatdı'), ('done', 'Tamamlandı'), ('pending', 'Təxirə salındı'), ('rejected', 'Rədd edildi')], default='todo', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='users.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_services', to='tasks.service')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_services', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskServiceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charfield_value', models.CharField(blank=True, max_length=255, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('image_value', models.ImageField(blank=True, null=True, upload_to=tasks.models.task.task_service_upload_path)),
                ('file_value', models.FileField(blank=True, null=True, upload_to=tasks.models.task.task_service_upload_path)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('number_value', models.IntegerField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_values', to='tasks.column')),
                ('task_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tasks.taskservice')),
            ],
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['customer'], name='tasks_task_custome_8a09c5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='tasks_task_assigne_ab55af_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['group'], name='tasks_task_group_i_b1ce1d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskservice',
            index=models.Index(fields=['task'], name='tasks_tasks_task_id_d8ace8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskservice',
            index=models.Index(fields=['service'], name='tasks_tasks_service_964d06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskservice',
            unique_together={('task', 'service')},
        ),
        migrations.AddIndex(
            model_name='taskservicevalue',
            index=models.Index(fields=['task_service'], name='tasks_tasks_task_se_fd8475_idx'),
        ),
        migrations.AddIndex(
            model_name='taskservicevalue',
            index=models.Index(fields=['column'], name='tasks_tasks_column__ea3534_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskservicevalue',
            unique_together={('task_service', 'column')},
        ),
    ]
