# Generated by Django 5.2.6 on 2026-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_customer_task_taskservice_taskservicevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.service'),
        ),
    ]
