# Generated by Django 5.2.6 on 2026-01-31 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='longitude',
        ),
    ]
