# Generated by Django 5.2.6 on 2026-02-01 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_latitude_remove_task_longitude'),
        ('warehouse', '0002_add_returned_by_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('is_deducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_products', to='warehouse.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_products', to='tasks.task')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_products', to='warehouse.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['task'], name='tasks_taskp_task_id_4aa698_idx'), models.Index(fields=['product'], name='tasks_taskp_product_43a968_idx'), models.Index(fields=['warehouse'], name='tasks_taskp_warehou_6cc448_idx')],
            },
        ),
    ]
