# Generated by Django 5.2.6 on 2026-02-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_add_task_product_model'),
        ('warehouse', '0002_add_returned_by_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.ImageField(upload_to='task_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='tasks.task')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_documents', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task'], name='tasks_taskd_task_id_d5e8fd_idx'), models.Index(fields=['warehouse'], name='tasks_taskd_warehou_75788e_idx')],
            },
        ),
    ]
