# Generated by Django 5.2.6 on 2026-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_add_task_document_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdocument',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
