# Generated by Django 5.2.6 on 2026-02-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_add_confirmed_to_task_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdocument',
            name='file',
            field=models.FileField(upload_to='task_documents/'),
        ),
    ]
