# Generated by Django 5.2.6 on 2026-02-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_change_image_to_file_field'),
        ('warehouse', '0002_add_returned_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdocument',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.stockmovement'),
        ),
    ]
