# Generated by Django 5.2.6 on 2026-02-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_add_stock_movement_to_document'),
        ('warehouse', '0002_add_returned_by_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rəf',
                'verbose_name_plural': 'Rəflər',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tasks.shelf'),
        ),
        migrations.AddIndex(
            model_name='taskdocument',
            index=models.Index(fields=['confirmed'], name='tasks_taskd_confirm_75b19a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdocument',
            index=models.Index(fields=['shelf'], name='tasks_taskd_shelf_i_310909_idx'),
        ),
    ]
