# Generated by Django 5.2.6 on 2026-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tasktype_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdocument',
            name='stock_movement_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
