import 'package:flutter/material.dart';

/// Ant Design icon **names** sent to API; Material icons for preview only.
class AdminServiceIconOption {
  const AdminServiceIconOption({required this.name, required this.label});

  final String name;
  final String label;
}

const List<AdminServiceIconOption> kAdminServiceIconOptions = [
  AdminServiceIconOption(name: 'AudioOutlined', label: 'Səs / Audio'),
  AdminServiceIconOption(name: 'SoundOutlined', label: 'Səs Dalğası'),
  AdminServiceIconOption(name: 'CustomerServiceOutlined', label: 'Müştəri Xidməti'),
  AdminServiceIconOption(name: 'PhoneOutlined', label: 'Telefon'),
  AdminServiceIconOption(name: 'MobileOutlined', label: 'Mobil'),
  AdminServiceIconOption(name: 'MessageOutlined', label: 'Mesaj'),
  AdminServiceIconOption(name: 'CommentOutlined', label: 'Şərh'),
  AdminServiceIconOption(name: 'NotificationOutlined', label: 'Bildiriş'),
  AdminServiceIconOption(name: 'WifiOutlined', label: 'Wi-Fi / Internet'),
  AdminServiceIconOption(name: 'GlobalOutlined', label: 'Global / Internet'),
  AdminServiceIconOption(name: 'CloudOutlined', label: 'Cloud / Bulud'),
  AdminServiceIconOption(name: 'ApiOutlined', label: 'API / Əlaqə'),
  AdminServiceIconOption(name: 'LinkOutlined', label: 'Link / Bağlantı'),
  AdminServiceIconOption(name: 'SignalFilled', label: 'Siqnal'),
  AdminServiceIconOption(name: 'DesktopOutlined', label: 'TV / Monitor'),
  AdminServiceIconOption(name: 'PlaySquareOutlined', label: 'TV Kanalları'),
  AdminServiceIconOption(name: 'VideoCameraOutlined', label: 'Video / Kamera'),
  AdminServiceIconOption(name: 'PlayCircleOutlined', label: 'Play / Oynat'),
  AdminServiceIconOption(name: 'YoutubeOutlined', label: 'YouTube / Video'),
  AdminServiceIconOption(name: 'CameraOutlined', label: 'Kamera'),
  AdminServiceIconOption(name: 'PictureOutlined', label: 'Şəkil'),
  AdminServiceIconOption(name: 'LaptopOutlined', label: 'Laptop'),
  AdminServiceIconOption(name: 'TabletOutlined', label: 'Tablet'),
  AdminServiceIconOption(name: 'PrinterOutlined', label: 'Printer'),
  AdminServiceIconOption(name: 'UsbOutlined', label: 'USB'),
  AdminServiceIconOption(name: 'HddOutlined', label: 'Disk / HDD'),
  AdminServiceIconOption(name: 'ToolOutlined', label: 'Təmir / Alət'),
  AdminServiceIconOption(name: 'SettingOutlined', label: 'Parametrlər'),
  AdminServiceIconOption(name: 'ThunderboltOutlined', label: 'Elektrik'),
  AdminServiceIconOption(name: 'BulbOutlined', label: 'İşıq / İdea'),
  AdminServiceIconOption(name: 'DatabaseOutlined', label: 'Database'),
  AdminServiceIconOption(name: 'CodeOutlined', label: 'Kod / Proqram'),
  AdminServiceIconOption(name: 'HomeOutlined', label: 'Ev'),
  AdminServiceIconOption(name: 'ShopOutlined', label: 'Mağaza'),
  AdminServiceIconOption(name: 'BankOutlined', label: 'Bank / Ofis'),
  AdminServiceIconOption(name: 'EnvironmentOutlined', label: 'Yer / Lokasiya'),
  AdminServiceIconOption(name: 'BuildOutlined', label: 'Tikinti'),
  AdminServiceIconOption(name: 'ApartmentOutlined', label: 'Bina / Şirkət'),
  AdminServiceIconOption(name: 'CarOutlined', label: 'Avtomobil'),
  AdminServiceIconOption(name: 'RocketOutlined', label: 'Sürətli Xidmət'),
  AdminServiceIconOption(name: 'SafetyOutlined', label: 'Təhlükəsizlik'),
  AdminServiceIconOption(name: 'LockOutlined', label: 'Kilid'),
  AdminServiceIconOption(name: 'EyeOutlined', label: 'Nəzarət'),
  AdminServiceIconOption(name: 'SecurityScanOutlined', label: 'Skan'),
  AdminServiceIconOption(name: 'AppstoreOutlined', label: 'Tətbiq'),
  AdminServiceIconOption(name: 'ExperimentOutlined', label: 'Laboratoriya'),
  AdminServiceIconOption(name: 'GiftOutlined', label: 'Hədiyyə'),
  AdminServiceIconOption(name: 'DollarOutlined', label: 'Ödəniş'),
  AdminServiceIconOption(name: 'CreditCardOutlined', label: 'Kart'),
  AdminServiceIconOption(name: 'ClockCircleOutlined', label: 'Saat / Vaxt'),
  AdminServiceIconOption(name: 'CalendarOutlined', label: 'Təqvim'),
  AdminServiceIconOption(name: 'TeamOutlined', label: 'Komanda'),
  AdminServiceIconOption(name: 'UserOutlined', label: 'İstifadəçi'),
];

final Map<String, IconData> _kServiceIconPreview = {
  'AudioOutlined': Icons.audiotrack,
  'SoundOutlined': Icons.graphic_eq,
  'CustomerServiceOutlined': Icons.support_agent,
  'PhoneOutlined': Icons.phone,
  'MobileOutlined': Icons.smartphone,
  'MessageOutlined': Icons.message,
  'CommentOutlined': Icons.comment,
  'NotificationOutlined': Icons.notifications,
  'WifiOutlined': Icons.wifi,
  'GlobalOutlined': Icons.public,
  'CloudOutlined': Icons.cloud,
  'ApiOutlined': Icons.api,
  'LinkOutlined': Icons.link,
  'SignalFilled': Icons.signal_cellular_alt,
  'DesktopOutlined': Icons.desktop_windows,
  'PlaySquareOutlined': Icons.video_library,
  'VideoCameraOutlined': Icons.videocam,
  'PlayCircleOutlined': Icons.play_circle_outline,
  'YoutubeOutlined': Icons.play_circle,
  'CameraOutlined': Icons.camera_alt,
  'PictureOutlined': Icons.image,
  'LaptopOutlined': Icons.laptop,
  'TabletOutlined': Icons.tablet,
  'PrinterOutlined': Icons.print,
  'UsbOutlined': Icons.usb,
  'HddOutlined': Icons.storage,
  'ToolOutlined': Icons.build,
  'SettingOutlined': Icons.settings,
  'ThunderboltOutlined': Icons.bolt,
  'BulbOutlined': Icons.lightbulb_outline,
  'DatabaseOutlined': Icons.storage,
  'CodeOutlined': Icons.code,
  'HomeOutlined': Icons.home,
  'ShopOutlined': Icons.store,
  'BankOutlined': Icons.account_balance,
  'EnvironmentOutlined': Icons.place,
  'BuildOutlined': Icons.construction,
  'ApartmentOutlined': Icons.apartment,
  'CarOutlined': Icons.directions_car,
  'RocketOutlined': Icons.rocket_launch,
  'SafetyOutlined': Icons.health_and_safety,
  'LockOutlined': Icons.lock,
  'EyeOutlined': Icons.visibility,
  'SecurityScanOutlined': Icons.security,
  'AppstoreOutlined': Icons.apps,
  'ExperimentOutlined': Icons.science,
  'GiftOutlined': Icons.card_giftcard,
  'DollarOutlined': Icons.attach_money,
  'CreditCardOutlined': Icons.credit_card,
  'ClockCircleOutlined': Icons.access_time,
  'CalendarOutlined': Icons.calendar_today,
  'TeamOutlined': Icons.groups,
  'UserOutlined': Icons.person,
};

IconData adminServiceIconPreview(String? antName) {
  if (antName == null || antName.isEmpty) return Icons.apps;
  return _kServiceIconPreview[antName] ?? Icons.apps;
}
