# Generated by Django 5.2.6 on 2026-02-08 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_remove_taskdocument_shelf_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rəf',
                'verbose_name_plural': 'Rəflər',
                'db_table': 'tasks_shelf',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_movement_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='task_documents/')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_documents', to=settings.AUTH_USER_MODEL)),
                ('shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.shelf')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.stockmovement')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='tasks.task')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_documents', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'tasks_taskdocument',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task'], name='tasks_taskd_task_id_d5e8fd_idx'), models.Index(fields=['warehouse'], name='tasks_taskd_warehou_75788e_idx'), models.Index(fields=['confirmed'], name='tasks_taskd_confirm_75b19a_idx'), models.Index(fields=['shelf'], name='tasks_taskd_shelf_i_310909_idx')],
            },
        ),
    ]
