# Generated by Django 5.2.6 on 2026-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskdocument',
            name='tasks_taskd_warehou_75788e_idx',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='stock_movement_title',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='action',
            field=models.CharField(blank=True, help_text='Prosesin açıqlaması', max_length=255, null=True),
        ),
    ]
