# Generated by Django 5.2.6 on 2026-01-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_warehouse_reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_warehouse_writer',
            field=models.BooleanField(default=False),
        ),
    ]
