# Generated by Django 5.2.6 on 2026-01-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_is_admin_role_is_super_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
