# Generated by Django 5.2.6 on 2026-02-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userlocation_locationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_document_reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_document_writer',
            field=models.BooleanField(default=False),
        ),
    ]
